### ISSUE TITLE
count all the subgraphs

### ISSUE THREAD

**Issue by loloDawit** [loloDawit/ESU-Algorithm#2]
I am working on save to file method, and I need the total number of subgraphs that are generated at the end. Right now what I have is a global variable `int count = 0` and I called it inside the`showTree()` method, it returns `78` which is the total number of leaves in the tree. But I only need the bottom level that has the subgraph.

**Comment by MrClassic** [comment]
I'll implement it. The ESUTree has a getLeaves() method. If called on the last tree in the treeList, it will return a list of leaf nodes. Then it's just asking the list for its size
